services:
  db:
    image: postgres:latest
    container_name: todo-list-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ewsd
      POSTGRES_DB: TodoListAppDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: